image: Visual Studio 2017
clone_depth: 1
init:
  - git config --global core.autocrlf input
before_build:
  - dotnet --version
build_script:
  - dotnet build -c Debug
  - cd package
  - package\Package.bat
test_script:
  - dotnet test -c Debug
artifacts:
  - path: package\*.nupkg

