image: Visual Studio 2017
clone_depth: 1
init:
  - git config --global core.autocrlf input
before_build:
  - dotnet --version
build_script:
  - dotnet build -c Debug
test_script:
  - ps: .\runTests.ps1
after_test:
- cd package && Package.bat %appveyor_build_number%
artifacts:
  - path: package\*.nupkg  
deploy:
- provider: NuGet
  api_key:
    secure: Sxj62OR5YCdm+9V4TEoz4LxwNEFBP6hQbf9P2mbuhxNpz3XRt53b3ehWrRfJqXtk
  skip_symbols: false
  on:
    branch: master
