image: Visual Studio 2017
clone_depth: 1
init:
  - git config --global core.autocrlf input
before_build:
  - dotnet --version
build_script:
  - dotnet build -c Debug
  - cd package && Package.bat
test_script:
  - ps: .\runTests.ps1
artifacts:
  - path: package\*.nupkg  
deploy:
- provider: NuGet
  api_key:
    secure: Mr/1en3q5idICN9+Y6u+WZGMD48LMCEkv838giL+3VJx5851xIIHdGoHwFe++hE+
  skip_symbols: false
  on:
    branch: master
