image: Visual Studio 2017
clone_depth: 1
init:
  - git config --global core.autocrlf input
before_build:
  - dotnet --version
build_script:
  - dotnet build -c Debug
  - cd package && Package.bat %appveyor_build_number%
test_script:
  - ps: .\runTests.ps1
artifacts:
  - path: package\*.nupkg  
deploy:
- provider: NuGet
  api_key:
    secure: rnTzJ/pJIUzQFG/4rgpTSS4e/hcGtMYCefYxq3r5s57aD2j/xuhKadv/qF6zHjhK
  skip_symbols: false
  on:
    branch: master
